### ISSUE TITLE
How recall modal with a simple link ?

### ISSUE THREAD

**Issue by foutesting** [statikbe/laravel-cookie-consent#12]
The user has just validated the modal window of the cookies. He made a mistake and would like to return to it. What is the code or the function that allows to do it  in blade (href ?)
Thank

**Comment by dduupp** [comment]
You should be able to create a link (or button) that does so by using this class: `js-lcc-settings-toggle`
For example: `<a href="javascript:void(0)" class="js-lcc-settings-toggle">Change cookie preferences</a>`

**Comment by foutesting** [comment]
Thank a lot !
