### ISSUE TITLE
Should document very briefly how to use in GTM e.g.

### ISSUE THREAD

**Issue by peterabarry** [statikbe/laravel-cookie-consent#2]
<img width="656" alt="customvar" src="https://user-images.githubusercontent.com/963982/82126817-07896980-97a7-11ea-9102-81cb9a575fad.png">

Mine may be wrong which is kinda my point. Connect the dots if poss. 

Nice simple solution though, improved on  spatie cousin, thanks.

**Comment by kristofser** [comment]
Hey, sorry for the really late response...

We were still somewhat tinkering with the settings and module itself.. 
But beginning of next week I will be updating the readme with extra information and screenshots about how to configure this in Google Tag Manager.

**Comment by kristofser** [comment]
@peterabarry, 

I've added more documentation on how to configure this all in Google Tag Manager.
It's a step by step guide with screenshots, so I hope it's clear enough.

**Comment by peterabarry** [comment]
nice one thanks
