### ISSUE TITLE
Question: How to configure with Facebook Pixel?

### ISSUE THREAD

**Issue by albertpratomo** [statikbe/laravel-cookie-consent#21]
Hi, I see that a tutorial is given for the GTM integration [here](https://github.com/statikbe/laravel-cookie-consent/blob/master/docs/google-tag-manager.md)

Do you have any tutorial how to configure this with Facebook Pixel?

Thanks in advance

**Comment by kristofser** [comment]
Hi @albertpratomo 
I'm sorry, we don't have a tutorial for that, because we rarely use Facebook Pixel.

If you have such tutorial you can always add a pull request and I would be happy to integrate it in our documentation.
