### ISSUE TITLE
ignored_paths 

### ISSUE THREAD

**Issue by Hodakh** [statikbe/laravel-cookie-consent#25]
I don't want the modal to be shown on certain pages, so I must add the route to ignored_paths array in the config file. For a route as 'admin/users' every thing is fine but for a route as 'admin/user/{id}' it doesn't work. How can I fix it or how can say all the routes which start with '/admin' don't show the cookie policy?

**Comment by jaapboerma** [comment]
I have had success with this by using a [Route Group](https://laravel.com/docs/7.x/routing#route-group-middleware) (in a Laravel 7 application) like this: 

```
<?php
use \Statikbe\CookieConsent\CookieConsentMiddleware;

include 'web/admin.php';

Route::middleware([CookieConsentMiddleware::class])->group(function () {
    include 'web/website.php';
});
```

My admin routes are excluded from consent. In  `config/cookie-consent.php`, I excluded the login page by using `'ignored_paths' => ['/login']`. 

Result: all visitors see the consent, all admins do not.

**Comment by kristofser** [comment]
We've changed the way of handling the ignored paths:


**Don't show modal on cookie policy page or other pages**
If you don't want the modal to be shown on certain pages you can add the relative url to the ignored paths setting. This also accepts wildcards (see the Laravel Str::is() [helper](https://laravel.com/docs/9.x/helpers#method-str-is)).

`'ignored_paths => ['/en/cookie-policy', '/api/documentation*'];`
