### ISSUE TITLE
GTM Configuration Issue

### ISSUE THREAD

**Issue by soonleh** [statikbe/laravel-cookie-consent#26]
Hi, I have followed the steps in GTM configuration provided here (https://github.com/statikbe/laravel-cookie-consent/blob/master/docs/google-tag-manager.md). But I am not sure of two things:
1. In the screenshot, there is no showing that the GDPR - Consent for marketing cookies trigger should be added but it was mentioned in Step 7. So, which way is correct?
2. I faced this error when trying to publish the changes --> 
Invalid “Google Analytics Settings” field | Google Analytics | Incompatible variable reference “Event” found in this tag. Please either revert your changes or update the “Google Analytics Settings” field in the tag.

Any help will be appreciated.

**Comment by kristofser** [comment]
Hey @soonleh 

As stated in step 6, first you create the marketing trigger (just like in the screenshot in step 6)

Afterwards (step 7) you add the trigger  to all the tags that have to do with Marketing:
<img width="796" alt="image" src="https://user-images.githubusercontent.com/5928907/142171935-3a694dd8-a4af-4c10-82c4-8d23a09ef255.png">

This is like documented in step 3 and 5  (no consent and analytics trigger).

Your part 2 error with Google Analytics Settings has something to do with with this tag I think:
<img width="784" alt="image" src="https://user-images.githubusercontent.com/5928907/142172553-2866564e-bf40-499a-a7fd-0a9d47318716.png">
But I don't know what the Variable "Event" is in your case. If this has something to do with step 1 with the naming of your variable.

If you have any more questions, just let me know.
