### ISSUE TITLE
Cookies still present after withdrawing consent

### ISSUE THREAD

**Issue by sutcliffe121** [statikbe/laravel-cookie-consent#35]
I have implemented the package with GTM for my site but I think I might have a problem in the scenario where a user accepts all cookies but then changes their mind using the adjust preferences link.

Reproduction steps:
1. Load the website and observe the cookie pop up and only essential cookies are set (using Chrome Dev Tools)
2. Click 'accept all cookies'. Observe the cookie pop up closes and GA cookies are also set
3. In the footer of the site, click 'adjust your preferences' and untick analytical and marketing cookies. Click 'save my selection'.

Actual behavior:
GA cookies remain and are still set

Expected behavior:
GA cookies are removed and only essential cookies are set

Is this expected or a bug?

I have re-checked that I followed all of the GTM steps as per the documentation:
![image](https://user-images.githubusercontent.com/33236577/163544739-7cca08f0-0dc6-456d-bdee-f00443decc1c.png)

**Comment by kristofser** [comment]
Hey thank you for this issue, we're going to look into it asap.
Seems to be something wrong in Tag Manager configuration .

**Comment by sutcliffe121** [comment]
Great - thanks. Let me know if you need anymore details.

**Comment by sutcliffe121** [comment]
Hi @kristofser, did you manage to take a look at the issue, any thoughts?

**Comment by sutcliffe121** [comment]
I see this is also an issue on your staik.be website. If a user provides consent, but then changes their mind, GA cookies are still set.

You can see below, my cookie consent is set to false, but GA cookies are still there:
![image](https://user-images.githubusercontent.com/33236577/192880784-f538781b-e2cc-44bf-8c2a-44016d0695c3.png)

**Comment by kristofser** [comment]
Hi sorry for the late reply.

I've planned in our marketing team (next tuesday) to check this issue out because this looks like some weird Tagmanager issue. I'll keep you posted asap.

**Comment by kristofser** [comment]
Hi @sutcliffe121 
I've checked this issue with some people, and the fact that these cookies remain is normal behaviour. These are Google cookies (or any other cookies for that matter). We don't delete any cookie that is present.
We just put our __cookie_consent to false which means that when  Google Tag Manager that has been configured, it won't track anything anymore.

**Comment by martinschenk** [comment]
Thanks for the answer. I had the same "problem".
