### ISSUE TITLE
Allow navigation with essential cookies

### ISSUE THREAD

**Issue by jcerdan** [statikbe/laravel-cookie-consent#37]
Hi,

is it possible to allow website navigation with essential cookies and show banner on every page until the user takes a decision?
I have installed the package and banner shows right but all buttons, menu etc.. on the page is disabled.
I have seen "inert" is added to DOM elements but don't know how to disable that and if there's an option.

**Comment by kristofser** [comment]
Hi, 
Sadly enough this is something we won't be implementing. We actually want people to accept some form of cookies, (essential, analytic, marketing..) before they access the website. 
Most major websites in our country have it implemented this way too.

This is why we have the link to the settings added in our documentation. So people can change their setting whenever they want.

`<a href="#" class="js-lcc-settings-toggle">@lang('cookie-consent::texts.alert_settings')</a>`
