### ISSUE TITLE
Modal doesn't open - Bootstrap conflict?

### ISSUE THREAD

**Issue by sutcliffe121** [statikbe/laravel-cookie-consent#45]
I have installed the package as per the docs and added a link in the footer to Manage Cookie Preferences.

<a href="javascript:void(0)" class="js-lcc-settings-toggle">Cookie Preferences</a>

The modal will not open. The only way I can get the modal to open is by removing my Bootstrap JS. Therefore I assume there is a conflict between the package JS and Bootstrap JS.

I have Googled the issue and see a lot of articles saying that href="javascript:void(0)" should not really be used.

Any ideas what the Bootstrap conflict may be, or is there an alternative way to open the modal rather than using href="javascript:void(0)"?

Thanks in advance.

**Comment by stijnelskens** [comment]
Hi @sutcliffe121 

Have you tried using `href="#"` instead of `void(0)` ?
This should work as well!

Let me know if you need any help!

**Comment by sutcliffe121** [comment]
After further investigation, we identified that this line is the problem/conflict:
window.$ = window.jQuery = require('jquery');

This line is in our bootstrap.js file which gets included in our main JS build. The way we call jquery appears to conflict with this packages JS.

If we remove the line above it works fine. Not sure on the best way to resolve it.
