### ISSUE TITLE
CSS and JS files throw 500 errors

### ISSUE THREAD

**Issue by geertjanknapen1** [statikbe/laravel-cookie-consent#47]
## **The problem**
On page load the CSS and JS files throw a 500 error. The HTML code is visible but `display: none;` is always active on it. See image below for reference. (the other 500 errors are just images)

Laravel 9, running in docker.

## **Steps to reproduce:**
1. Installed via composer `composer require statikbe/laravel-cookie-consent`

2. Published JS and CSS files as per documentation:
`php artisan vendor:publish --provider="Statikbe\CookieConsent\CookieConsentServiceProvider" --tag="public"`

3. Added stylesheet and js script in base blade.

4. Added as global middleware:
```
class Kernel extends HttpKernel
{
    protected $middleware = [
        // ...
        \Statikbe\CookieConsent\CookieConsentMiddleware::class,
    ];

    // ...
}
```

5. Cookie button snippet added in footer as per documentation:
`<a href="javascript:void(0)" class="js-lcc-modal-alert">Cookies prefs</a>`

6. Ran `php artisan cache:clear` and `php artisan view:clear`

## **Reference image:**
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/33750300/200815548-65165e15-92a4-4b6a-b396-cdcfb21bafd8.png">

**Comment by kristofser** [comment]
Hey @geertjanknapen1 

I did a clean setup of Laravel.

I'm running this project with [DDEV](https://ddev.com/) in Docker container.

Composer.json: 
```json
"require": {
        "php": "^8.1",
        "laravel/framework": "^9.3",
        "statikbe/laravel-cookie-consent": "^1.4"
    },
```

And followed the steps in de readme:
1) published assets to the public folder with
`php artisan vendor:publish --provider="Statikbe\CookieConsent\CookieConsentServiceProvider" --tag="public"
`

2) And added the CSS to my base layout:
`<link rel="stylesheet" type="text/css" href="{{asset("vendor/cookie-consent/css/cookie-consent.css")}}">
`
3) made sure the middleware is in my kernel:
```php
// app/Http/Kernel.php

class Kernel extends HttpKernel
{
    protected $middleware = [
        // ...
        \Statikbe\CookieConsent\CookieConsentMiddleware::class,
    ];

    // ...
}
```

And I added the settings link in my footer:
`<a href="javascript:void(0)" class="js-lcc-settings-toggle">@lang('cookie-consent::texts.alert_settings')</a>
`

The previous steps gave me this result: 
![image](https://user-images.githubusercontent.com/5928907/201674193-b841cd3e-fb3b-4f4b-92ae-7a0c4207d700.png)
![image](https://user-images.githubusercontent.com/5928907/201674591-da5198b6-5b63-408e-93af-b153e926cfec.png)
