### ISSUE TITLE
Can't understand step 3 of "How to configure Google Tag Manager"

### ISSUE THREAD

**Issue by ericc06** [statikbe/laravel-cookie-consent#7]
I started to follow the "How to configure Google Tag Manager" documentation.
I can't understand which GTM screen the step 3 is related to.

The title "Universal Analytics" that I can see in the screenshot is confusing me.
It is not mentioned in the previous steps.
Where does it come from? 

After step 2, when I click the "tag" tab as asked in step 3, I can't see anything looking like in the screenshot.

Also, in the screenshot provided in step 3, I can see that the type of "GDPR - Has not given censent" trigger is "Page View".
But in step 2 we created a "GDPR - Has not given censent" trigger of type "Custom Event".
Did I miss something?

By the way, thank you very much for this documentation which seems great!

**Comment by kristofser** [comment]
Hey @ericc06 

I made some modifications to the docs. Some things were indeed not that clear.
I hope this will help you out.

**Comment by ericc06** [comment]
Hi @kristofser 
Thank you very much for the added explanations.
Now, (almost) everything is OK and works as expected.

Just for your information, for my better understanding in GTM I respectively renamed "GDPR - Consent for analytical cookies" and "GDPR - Consent for marketing cookies" with "GDPR - No consent for analytical cookies" and "GDPR - No consent for marketing cookies".
It will help me if I need to handle this again in a far future.

I also noticed two minor bugs I am about to open.
