### ISSUE TITLE
Unexpected parenthesis in the Cookie settings pop-up

### ISSUE THREAD

**Issue by ericc06** [statikbe/laravel-cookie-consent#9]
[Package version: 1.2.1]

In the French version of the Cookie settings pop-up, the first paragraph ends with an unexpected closing parenthesis (see attached image).
This character is not present in the French translation of this sentence.

I can't figure out where this parenthesis comes from.

![unexpected_parenthesis](https://user-images.githubusercontent.com/29001191/92133481-bad6a680-ee08-11ea-9a75-09042d3f5a92.png)

**Comment by ericc06** [comment]
Reproduced with version 1.2.4.

**Comment by kristofser** [comment]
@ericc06 

There was an obsolete parenthesis in the index.tpl file. It has been removed.
